name: XXXXXX
description: XYZ

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+3

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  blobs: ^1.2.0
  cached_network_image: ^2.5.0
  cloud_firestore: ^0.14.0+2
  country_code_picker: ^1.6.2
  cupertino_icons: null
  date_field: ^0.3.3
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  firebase_messaging: ^8.0.0-dev.11
  # firebase_messaging: ^7.0.3
  firebase_storage: ^5.2.0
  flutter_incall: ^1.0.0
  flutter_device_type: ^0.3.2
  flutter_local_notifications: ^3.0.3
  flutter_signin_button: ^1.1.0
  flutter_svg: null
  flutter_swiper: ^1.1.6
  flutter_webrtc: ^0.5.8
  geocoder: ^0.2.1
  geoflutterfire: ^2.2.1
  geolocator: ^6.1.13
  get: ^3.17.1
  get_storage: ^1.3.2
  google_sign_in: ^4.5.6
  image_picker: ^0.6.7+15
  intl: ^0.16.0
  intl_phone_number_input: ^0.5.2+2
  just_audio: ^0.5.7
  permission_handler: ^5.0.1+1
  location_permissions: ^3.0.0+1
  photo_view: ^0.10.3
  share: ^0.6.5+4
  speech_to_text: ^3.1.0
  story_view: ^0.12.5
  swipe_to: ^0.0.1+8
  video_compress: ^2.1.1
  visibility_detector: ^0.1.5
  sign_in_with_apple: ^2.5.2
  crypto: ^2.1.5
  socket_io_client: ^0.9.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.3.1
  rename: ^1.2.0
  flutter_launcher_icons: ^0.8.1
  flutter_launcher_name: ^0.0.1
  flutter_native_splash: ^0.3.0
  flutter_sheet_localization_generator: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.
    - assets/logos/.
    - assets/navbar/.
    - assets/profile_page/bg/.
    - assets/profile_page/page1/.
    - assets/images/default.png
    - assets/images/defaultDark.png
    - assets/profile_page/page1/light/.
    - assets/profile_page/interests/.
    - assets/profile_page/interests/dark/.
    - assets/profile_page/interests_icon/.
    - assets/profile_page/facts/.
    - assets/login_register/voice_auth/.
    - assets/login_register/registeration/.
    - assets/login_register/onboarding/.
    - assets/theme_showcase/.
    - assets/rotate_screen/.
    - assets/match_screen/.
    - assets/settings/.

  fonts:
    - family: whatever
      fonts:
        - asset: assets/fonts/whatever.ttf
        - asset: assets/fonts/whatever_bold.ttf
          weight: 700
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans.ttf
        - asset: assets/fonts/WorkSans-Italic.ttf
          style: italic
    - family: Belinda
      fonts:
        - asset: assets/fonts/belinda.otf
    - family: Handlee
      fonts:
        - asset: assets/fonts/Handlee.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_native_splash:
  image: assets/logos/splash_screen.png
  color: 'ffffff'
  android_disable_fullscreen: true

flutter_icons:
  android: 'launcher_icon'
  ios: false
  image_path: 'assets/logos/XXXXX.png'