name: glics
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_bottom_navigation_bar: ^0.2.1
  animations: ^1.1.2
  badges: ^1.1.6
  cloud_firestore: ^0.14.3
  connectivity_wrapper: ^1.0.4
  cupertino_icons: ^1.0.2
  fancy_shimmer_image: ^1.2.0
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2
  flutter_automation: ^1.4.0
  flutter_launcher_icons: null
  font_awesome_flutter: ^8.8.1
  get: ^3.24.0
  line_icons: ^0.2.0
  lint: ^1.5.1
  provider: ^4.3.3
  timeago: ^3.0.1
  uuid: ^2.2.2
  velocity_x: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "images/logo.png"
  image_path_android: "images/logo.png"
  adaptive_icon_background: "images/background.png"
  adaptive_icon_foreground: "images/foreground.png"

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  fonts:
    - family: Tahoma
      fonts:
        - asset: images/TahomaRegularfont.ttf
